# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import financeapp_pb2 as financeapp__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in financeapp_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OperationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegistraUtente = channel.unary_unary(
                '/operation.Operation/RegistraUtente',
                request_serializer=financeapp__pb2.DatiUtente.SerializeToString,
                response_deserializer=financeapp__pb2.Conferma.FromString,
                _registered_method=True)
        self.AggiornaTicker = channel.unary_unary(
                '/operation.Operation/AggiornaTicker',
                request_serializer=financeapp__pb2.DatiUtente.SerializeToString,
                response_deserializer=financeapp__pb2.Conferma.FromString,
                _registered_method=True)
        self.CancellaUtente = channel.unary_unary(
                '/operation.Operation/CancellaUtente',
                request_serializer=financeapp__pb2.Email.SerializeToString,
                response_deserializer=financeapp__pb2.Conferma.FromString,
                _registered_method=True)
        self.RecuperaValore = channel.unary_unary(
                '/operation.Operation/RecuperaValore',
                request_serializer=financeapp__pb2.Email.SerializeToString,
                response_deserializer=financeapp__pb2.Valore.FromString,
                _registered_method=True)
        self.CalcolaMediaValori = channel.unary_unary(
                '/operation.Operation/CalcolaMediaValori',
                request_serializer=financeapp__pb2.DatiMediaValori.SerializeToString,
                response_deserializer=financeapp__pb2.Valore.FromString,
                _registered_method=True)


class OperationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegistraUtente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AggiornaTicker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancellaUtente(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecuperaValore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalcolaMediaValori(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OperationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegistraUtente': grpc.unary_unary_rpc_method_handler(
                    servicer.RegistraUtente,
                    request_deserializer=financeapp__pb2.DatiUtente.FromString,
                    response_serializer=financeapp__pb2.Conferma.SerializeToString,
            ),
            'AggiornaTicker': grpc.unary_unary_rpc_method_handler(
                    servicer.AggiornaTicker,
                    request_deserializer=financeapp__pb2.DatiUtente.FromString,
                    response_serializer=financeapp__pb2.Conferma.SerializeToString,
            ),
            'CancellaUtente': grpc.unary_unary_rpc_method_handler(
                    servicer.CancellaUtente,
                    request_deserializer=financeapp__pb2.Email.FromString,
                    response_serializer=financeapp__pb2.Conferma.SerializeToString,
            ),
            'RecuperaValore': grpc.unary_unary_rpc_method_handler(
                    servicer.RecuperaValore,
                    request_deserializer=financeapp__pb2.Email.FromString,
                    response_serializer=financeapp__pb2.Valore.SerializeToString,
            ),
            'CalcolaMediaValori': grpc.unary_unary_rpc_method_handler(
                    servicer.CalcolaMediaValori,
                    request_deserializer=financeapp__pb2.DatiMediaValori.FromString,
                    response_serializer=financeapp__pb2.Valore.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'operation.Operation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('operation.Operation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Operation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegistraUtente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/operation.Operation/RegistraUtente',
            financeapp__pb2.DatiUtente.SerializeToString,
            financeapp__pb2.Conferma.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AggiornaTicker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/operation.Operation/AggiornaTicker',
            financeapp__pb2.DatiUtente.SerializeToString,
            financeapp__pb2.Conferma.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancellaUtente(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/operation.Operation/CancellaUtente',
            financeapp__pb2.Email.SerializeToString,
            financeapp__pb2.Conferma.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecuperaValore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/operation.Operation/RecuperaValore',
            financeapp__pb2.Email.SerializeToString,
            financeapp__pb2.Valore.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalcolaMediaValori(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/operation.Operation/CalcolaMediaValori',
            financeapp__pb2.DatiMediaValori.SerializeToString,
            financeapp__pb2.Valore.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
